apiVersion: v1
kind: Service
metadata:
  name: {{ include "wireguard.fullname" . }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  internalTrafficPolicy: Cluster
  externalTrafficPolicy: Cluster
  ports:
    - port: 51820
      targetPort: 51820
      protocol: UDP
      name: wireguard
    {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
    {{ end }}
  selector:
    {{- include "wireguard.selectorLabels" . | nindent 4 }}
